# Second Docker Compose file
version: '3'

services:
  registry_postgres:
    image: postgres
    container_name: registry
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: registry_db
    ports:
      - "5543:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  registry_postgres_data:
