version: '3'

services:
  postgres:
    image: postgres
    container_name: stocks
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stocks
    ports:
      - "6543:5432"
    volumes:
      - ./csv:/csv
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
volumes:
  postgres_data:
